import IngredientPageTemplate, { IngredientData } from "@/components/ingredients/IngredientPageTemplate";

const ingredient: IngredientData = {
  name: "Vitamin C (L-Ascorbic Acid)",
  whatItIs: "Vitamin C, in its most bioactive form L-ascorbic acid, is a potent water-soluble antioxidant essential for cutaneous health. It functions as a cofactor for prolyl and lysyl hydroxylases, enzymes critical for collagen biosynthesis, while simultaneously neutralising reactive oxygen species generated by UV exposure and environmental pollutants. Various stable derivatives exist (ascorbyl glucoside, ascorbyl tetraisopalmitate, sodium ascorbyl phosphate), each with distinct penetration profiles and stability characteristics.",
  whatItHelpsWith: [
    "Neutralising free radicals and providing photoprotection when combined with SPF",
    "Inhibiting tyrosinase activity to reduce melanin synthesis",
    "Stimulating fibroblast proliferation and collagen production",
    "Brightening overall complexion and reducing sallowness",
    "Accelerating wound healing through enhanced collagen deposition",
    "Reducing the appearance of fine lines associated with photoageing"
  ],
  bestFor: ["Dull, sallow complexion", "Photodamaged skin", "Hyperpigmentation", "Early signs of ageing", "Prevention-focused skincare"],
  howItsUsed: "L-ascorbic acid formulations require pH levels between 2.5-3.5 for optimal penetration and are typically used at concentrations of 10-20%. Apply in the morning to cleansed, dry skin before SPF application. Store in dark, airtight packaging as L-ascorbic acid oxidises rapidly. Discard if the solution turns brown or develops an unusual odour. Stable derivatives may be preferable for those with sensitive skin or in humid climates.",
  pairsWellWith: ["Vitamin E (synergistic antioxidant protection)", "Ferulic acid (stabilises and enhances efficacy)", "Hyaluronic acid", "SPF (complementary photoprotection)", "Niacinamide"],
  clinicNote: "We frequently prescribe vitamin C as the cornerstone of a preventative anti-ageing protocol. For patients presenting with melasma or significant photodamage, we typically combine topical vitamin C with other tyrosinase inhibitors for enhanced efficacy. Those with reactive skin often tolerate derivatives such as ascorbyl glucoside better than L-ascorbic acid. Formulation quality is paramount — poorly stabilised products offer minimal clinical benefit.",
  clinicalSuitability: [
    "Indicated for patients seeking photoprotection enhancement",
    "Appropriate for early intervention in chronological and photoageing",
    "Beneficial for post-inflammatory hyperpigmentation management",
    "Suitable as adjunctive therapy following laser resurfacing (once re-epithelialisation is complete)",
    "Safe during pregnancy and lactation"
  ],
  useWithCaution: [
    "Sensitive or reactive skin types may experience stinging with L-ascorbic acid",
    "Those using high-strength retinoids may find layering challenging — consider alternate timing",
    "Patients prone to contact dermatitis should patch test new formulations",
    "Low-pH formulations may exacerbate active inflammatory conditions"
  ],
  notIdealFor: [
    "Highly sensitised or compromised skin barriers (stabilise barrier first)",
    "Immediately post-procedure before full re-epithelialisation",
    "Those who cannot tolerate low-pH formulations",
    "Patients with G6PD deficiency (theoretical concern with high-dose topical application)"
  ],
  commonConcerns: [
    "Photoageing",
    "Solar lentigines",
    "Post-inflammatory hyperpigmentation",
    "Melasma (as adjunctive therapy)",
    "Dull, uneven skin tone",
    "Fine lines and wrinkles",
    "Environmental damage prevention"
  ],
  productExamples: [
    {
      name: "Brightening Vitamin C Serum",
      description: "Potent antioxidant serum formulated to protect against environmental damage and enhance skin radiance.",
      link: "#"
    },
    {
      name: "Daily Radiance Booster",
      description: "Lightweight formula that helps fade dark spots and improve overall skin luminosity over time.",
      link: "#"
    },
    {
      name: "Vitamin C + E Defence Serum",
      description: "Synergistic blend of vitamins C and E to provide comprehensive antioxidant protection and visible brightening.",
      link: "#"
    }
  ]
};

const VitaminC = () => <IngredientPageTemplate ingredient={ingredient} />;
export default VitaminC;
